force-app/main/default/objects/CM_Players__c/CM_Players__c.object-meta.xml
<CustomObject>
    <label>CM Player</label>
    <nameField>
        <label>Players Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CM Players</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CM_Players__c/fields/CM_Avatar_File__c.field-meta.xml
<CustomField>
    <fullName>CM_Avatar_File__c</fullName>
    <defaultValue>&quot;default.png&quot;</defaultValue>
    <label>Avatar File</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CM_Players__c/fields/CM_Rank__c.field-meta.xml
<CustomField>
    <fullName>CM_Rank__c</fullName>
    <label>Rank</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CM_Tournament__c/CM_Tournament__c.object-meta.xml
<CustomObject>
    <label>CM Tournament</label>
    <nameField>
        <label>CM Tournament Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CM Tournaments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CM_Tournament__c/fields/CM_Location__c.field-meta.xml
<CustomField>
    <fullName>CM_Location__c</fullName>
    <label>Location</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CM_Tournament__c/fields/CM_Tournament_Type__c.field-meta.xml
<CustomField>
    <fullName>CM_Tournament_Type__c</fullName>
    <label>Tournament Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GLC</fullName>
                <default>true</default>
                <label>GLC</label>
            </value>
            <value>
                <fullName>Standard</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CM_Tournament_Result__c/CM_Tournament_Result__c.object-meta.xml
<CustomObject>
    <label>Tournament Result</label>
    <nameField>
        <displayFormat>TR-{00000}</displayFormat>
        <label>Tournament Result Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tournament Results</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CM_Tournament_Result__c/fields/CM_Deck_Used__c.field-meta.xml
<CustomField>
    <fullName>CM_Deck_Used__c</fullName>
    <description>If no description, show the picklist value</description>
    <formula>IF (  
OR ( ISBLANK(CM_Deck_Description__c), ISNULL(CM_Deck_Description__c) ) ,
TEXT( CM_Deck_Type__c ),
CM_Deck_Description__c
)</formula>
    <label>Deck Used</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CM_Tournament_Result__c/fields/CM_Player__c.field-meta.xml
<CustomField>
    <fullName>CM_Player__c</fullName>
    <label>Player</label>
    <referenceTo>CM_Players__c</referenceTo>
    <relationshipName>Tournament_Results</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CM_Tournament_Result__c/fields/CM_Record__c.field-meta.xml
<CustomField>
    <fullName>CM_Record__c</fullName>
    <inlineHelpText>&quot;0-0-0&quot;</inlineHelpText>
    <label>Record</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CM_Tournament_Result__c/fields/CM_Tournament__c.field-meta.xml
<CustomField>
    <fullName>CM_Tournament__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tournament</label>
    <referenceTo>CM_Tournament__c</referenceTo>
    <relationshipLabel>CM Tournament Results</relationshipLabel>
    <relationshipName>CM_Tournament_Results</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CM_Tournament_Result__c/fields/CM_Tournament_Name__c.field-meta.xml
<CustomField>
    <fullName>CM_Tournament_Name__c</fullName>
    <formula>CM_Tournament__r.Name</formula>
    <label>Tournament Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CM_Tournament_Result__c/fields/CM_Tournament_Standing__c.field-meta.xml
<CustomField>
    <fullName>CM_Tournament_Standing__c</fullName>
    <label>Tournament Standing</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CM_Tournament_Result__c/fields/CM_Tournament_Type__c.field-meta.xml
<CustomField>
    <fullName>CM_Tournament_Type__c</fullName>
    <label>Tournament Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GLC</fullName>
            </value>
            <value>
                <fullName>Standard</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CM_Controller.cls
public without sharing class CM_Controller {
    @AuraEnabled
    public static ViewModel getViewModel() {
		ViewModel vm = new ViewModel();
		vm.outboundModel = new OutboundViewModel();
		return vm;
	}

	public class ViewModel {
		@AuraEnabled
		public OutboundViewModel outboundModel;
	}

	//? data coming out of the database
	public class OutboundViewModel {
		@AuraEnabled
		public List<CM_Tournament_Result__c> allTournamentResults;

		@AuraEnabled
		public List<CM_Players__c> allPlayers;

		public OutboundViewModel() {
			this.allTournamentResults = getAllTournamentResults();
			this.allPlayers = getAllPlayers();
		}
	}

	// ------------------------------------------------------------------------------------------------------------------ //
	//? Functions used to populate the OutboundViewModel class
	@AuraEnabled
	public static List<CM_Tournament_Result__c> getAllTournamentResults() {
		return [
            SELECT Id, CM_Deck_Used__c, CM_Player__r.Name, CM_Tournament_Standing__c, CM_Tournament_Name__c, CM_Tournament__r.Name, CM_Tournament__r.CM_Tournament_Type__c, CM_Tournament__r.CM_Location__c, CM_Record__c 
			FROM CM_Tournament_Result__c 
			ORDER BY CM_Tournament_Standing__c ASC];
	}

	@AuraEnabled
	public static List<CM_Players__c> getAllPlayers() {
		return [
            SELECT Id, CM_Rank__c, CM_Avatar_File__c, Name 
			FROM CM_Players__c 
			ORDER BY CM_Rank__c ASC];
	}

	//? Helper class
	public static List<SObject> reverseList(List<SObject> incomingList) {
		System.debug(incomingList);
		Map<Integer, SObject> mapName = new Map<Integer, SObject>();
		Integer i = 1;
		for (SObject obj : incomingList) {
			mapName.put(i, obj);
			i++;
		}
		List<SObject> listName = new List<SObject>();
		for (Integer j = incomingList.size(); j > 0; j--) {
			listName.add(mapName.get(j));
		}
		System.debug(listName);
		return listName;
	}
}